{
 "title": "ML Dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Возрастание времени обработки запроса",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Увеличение кол-ва запросов за 10 минут",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(main_app_predictions_count[10m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Квантили предсказаний",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.05, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, main_app_predictions_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Среднее значение задержки",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "http_request_duration_seconds_sum / http_request_duration_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Потребление RAM",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}