services:
  main-app:  
    env_file:
      - ./.env
    build:
      dockerfile: Dockerfile
    ports:
      - "${MAIN_APP_PORT_VM}:${MAIN_APP_PORT}"
    volumes:
      - type: bind
        source: ./models
        target: /services/models