global:
  scrape_interval: 15s
  
  scrape_timeout: 10s
  

scrape_configs:
  # имя сборщика
  - job_name: 'scrapping-main-app'

    # c какой страницы собирать метрики?
    metrics_path: /metrics
    scheme: http
    
    static_configs:
    - targets:
      - fastapi_app:1702